# Don't print a new line at the start of the prompt
#add_newline = true

# Replace the "❯" symbol in the prompt
[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[➜ ](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Disable the AWS module; it's noisy
[aws]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = ""

[git_commit]
commit_hash_length = 7

[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 5

# Language configs might be useful when they're less wordy someday.

[ruby]
symbol = " "
format = "[$symbol($version )]($style)"

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"

[status]
disabled = false
format = "[$status]($style) "

[vagrant]
disabled = true
