#!/usr/bin/env bash
#MISE dir="{{cwd}}"

touch mise.local.toml

# [env]
# BUNDLE_BIN = './.direnv/bin'
# GEM_HOME = './.direnv/ruby'
mise config set -f mise.local.toml env.BUNDLE_BIN './.direnv/bin'
mise config set -f mise.local.toml env.GEM_HOME './.direnv/ruby'

# [env._]
# path = [
#   "{{env.GEM_HOME}}/bin",
#   "{{env.BUNDLE_BIN}}"
# ]
mise config set -f mise.local.toml env._.path --type list "{{env.GEM_HOME}}/bin","{{env.BUNDLE_BIN}}"
